{% set name = "pytest-qt" %}
{% set version = "4.5.0" %}
{% set hash = "51620e01c488f065d2036425cbc1cbcf8a6972295105fd285321eb47e66a319f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/p/pytest-qt/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  script: python -m pip install . --no-deps --ignore-installed
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - pytest
    - pluggy >=1.1

test:
  requires:
    - pyqt 5.*
    - pytest
    - python {{ python_min }}
  imports:
    - pytestqt
  commands:
    - pytest --help

about:
  home: https://github.com/pytest-dev/pytest-qt
  license: MIT
  license_file: LICENSE
  summary: pytest support for PyQt and PySide applications
  doc_url: http://pytest-qt.readthedocs.io/en/latest/
  dev_url: https://github.com/pytest-dev/pytest-qt

extra:
  recipe-maintainers:
    - nicoddemus
